VAR float_goblin_trust = 0

CONST STRING_ITEM_STONE = "Stone"
CONST STRING_ITEM_MEAT = "Meat"
CONST STRING_ITEM_SMALL_KEY = "SmallKey"
CONST STRING_ITEM_BIG_KEY = "BigKey"

CONST STRING_NPC_GOBLIN = "Goblin"

CONST STRING_WHERE_IN_CELL = "inCell"
CONST STRING_WHERE_BEFORE_IRRWISH = "beforeIrrwish"